// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Alquiler
{
    public int id_alquiler { get; set; }

    public int id_cliente { get; set; }

    public int id_estado_alquiler { get; set; }

    public decimal monto { get; set; }

    public DateTime fecha_inicio { get; set; }

    public DateTime? fecha_fin { get; set; }

    public int id_vehiculo { get; set; }

    public int id_sucursal { get; set; }

    public virtual Cliente id_clienteNavigation { get; set; }

    public virtual Estados_Alquiler id_estado_alquilerNavigation { get; set; }

    public virtual Sucursal id_sucursalNavigation { get; set; }

    public virtual Vehiculo id_vehiculoNavigation { get; set; }
}