// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Barrio
{
    public int id_barrio { get; set; }

    public string barrio1 { get; set; }

    public int id_localidad { get; set; }

    public virtual ICollection<Sucursal> Sucursales { get; set; } = new List<Sucursal>();

    public virtual Localidad id_localidadNavigation { get; set; }
}