// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Cliente
{
    public int id_cliente { get; set; }

    public string nombre { get; set; }

    public string documento { get; set; }

    public int id_tipo_documento { get; set; }

    public virtual ICollection<Alquiler> Alquileres { get; set; } = new List<Alquiler>();

    public virtual ICollection<Contacto> Contactos { get; set; } = new List<Contacto>();

    public virtual Tipos_Documento id_tipo_documentoNavigation { get; set; }
}