// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Contacto
{
    public int id_contacto { get; set; }

    public int id_tipo_contacto { get; set; }

    public string contacto1 { get; set; }

    public int? id_cliente { get; set; }

    public virtual Cliente id_clienteNavigation { get; set; }

    public virtual Tipos_Contacto id_tipo_contactoNavigation { get; set; }
}