// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Estados_Alquiler
{
    public int id_estado_alquiler { get; set; }

    public string estado { get; set; }

    public virtual ICollection<Alquiler> Alquileres { get; set; } = new List<Alquiler>();
}