// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Provincia
{
    public int id_provincia { get; set; }

    public string provincia1 { get; set; }

    public virtual ICollection<Localidad> Localidades { get; set; } = new List<Localidad>();
}