// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Sucursal
{
    public int id_sucursal { get; set; }

    public string descripcion { get; set; }

    public int id_barrio { get; set; }

    public virtual ICollection<Alquiler> Alquileres { get; set; } = new List<Alquiler>();

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();

    public virtual ICollection<Vehiculo> Vehiculos { get; set; } = new List<Vehiculo>();

    public virtual Barrio id_barrioNavigation { get; set; }
}