// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Tipos_Contacto
{
    public int id_tipo_contacto { get; set; }

    public string tipo { get; set; }

    public virtual ICollection<Contacto> Contactos { get; set; } = new List<Contacto>();
}