// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Usuarios_Empleado
{
    public int id_usuario { get; set; }

    public string usuario { get; set; }

    public string contraseña { get; set; }

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();
}