// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApi_TPI_AIRCNR_PII.Models;

public partial class Vehiculo
{
    public int id_vehiculo { get; set; }

    public string patente { get; set; }

    public int id_tipo_vehiculo { get; set; }

    public int id_marca { get; set; }

    public string modelo { get; set; }

    public decimal valor_tasado { get; set; }

    public int id_estado_vehiculo { get; set; }

    public int id_sucursal { get; set; }

    public virtual ICollection<Alquiler> Alquileres { get; set; } = new List<Alquiler>();

    public virtual Estados_Vehiculo id_estado_vehiculoNavigation { get; set; }

    public virtual Marca id_marcaNavigation { get; set; }

    public virtual Sucursal id_sucursalNavigation { get; set; }

    public virtual Tipos_Vehiculo id_tipo_vehiculoNavigation { get; set; }
}